PracticaMVC/Models/ErrorViewModel.cs
namespace PracticaMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaMVC/Models/equiposDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace PracticaMVC.Models
{
    public class equiposDbContext : DbContext
    {
        public equiposDbContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<marcas> marcas { get; set; }
    }
}

PracticaMVC/Models/marcas.cs
using System.ComponentModel.DataAnnotations;

namespace PracticaMVC.Models
{
    public class marcas
    {
        [Key]
        [Display(Name = "ID")]
        public int id_marcas { get; set; }
        [Display(Name = "Nombre de la Marca")]
        public string? nombre_marca { get; set; }
        [Display(Name = "Estado")]
        public string? estados { get; set; }
    }
}

PracticaMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMVC.Models;
using System.Diagnostics;

namespace PracticaMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaMVC/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PracticaMVC.Models;

namespace PracticaMVC.Controllers
{
    public class MarcasController : Controller
    {
        private readonly equiposDbContext _context;

        public MarcasController(equiposDbContext context)
        {
            _context = context;
        }

        // GET: Marcas
        public async Task<IActionResult> Index()
        {
            return View(await _context.marcas.ToListAsync());
        }

        // GET: Marcas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marcas = await _context.marcas
                .FirstOrDefaultAsync(m => m.id_marcas == id);
            if (marcas == null)
            {
                return NotFound();
            }

            return View(marcas);
        }

        // GET: Marcas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marcas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_marcas,nombre_marca,estados")] marcas marcas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(marcas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marcas);
        }

        // GET: Marcas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marcas = await _context.marcas.FindAsync(id);
            if (marcas == null)
            {
                return NotFound();
            }
            return View(marcas);
        }

        // POST: Marcas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_marcas,nombre_marca,estados")] marcas marcas)
        {
            if (id != marcas.id_marcas)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(marcas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!marcasExists(marcas.id_marcas))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marcas);
        }

        // GET: Marcas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marcas = await _context.marcas
                .FirstOrDefaultAsync(m => m.id_marcas == id);
            if (marcas == null)
            {
                return NotFound();
            }

            return View(marcas);
        }

        // POST: Marcas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var marcas = await _context.marcas.FindAsync(id);
            if (marcas != null)
            {
                _context.marcas.Remove(marcas);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool marcasExists(int id)
        {
            return _context.marcas.Any(e => e.id_marcas == id);
        }
    }
}

PracticaMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticaMVC/Views/Marcas/Create.cshtml
@model PracticaMVC.Models.marcas

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>marcas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre_marca" class="control-label"></label>
                <input asp-for="nombre_marca" class="form-control" />
                <span asp-validation-for="nombre_marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estados" class="control-label"></label>
                <input asp-for="estados" class="form-control" />
                <span asp-validation-for="estados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaMVC/Views/Marcas/Delete.cshtml
@model PracticaMVC.Models.marcas

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>marcas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre_marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre_marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estados)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estados)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id_marcas" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PracticaMVC/Views/Marcas/Details.cshtml
@model PracticaMVC.Models.marcas

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>marcas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre_marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre_marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estados)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estados)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id_marcas">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PracticaMVC/Views/Marcas/Edit.cshtml
@model PracticaMVC.Models.marcas

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>marcas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id_marcas" />
            <div class="form-group">
                <label asp-for="nombre_marca" class="control-label"></label>
                <input asp-for="nombre_marca" class="form-control" />
                <span asp-validation-for="nombre_marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estados" class="control-label"></label>
                <input asp-for="estados" class="form-control" />
                <span asp-validation-for="estados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaMVC/Views/Marcas/Index.cshtml
@model IEnumerable<PracticaMVC.Models.marcas>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre_marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estados)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre_marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estados)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id_marcas">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id_marcas">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id_marcas">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PracticaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marcas" asp-action="Index">Marcas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PracticaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>